config/routes.rb
Rails.application.routes.draw do
  resources :provinces
  resources :customers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'finder#index'
  get '/finder', :to => 'finder#index', :as => 'finder'
  get '/missing_email', :to => 'finder#missing_email', :as => 'missing_emails'
  get '/alphabetized', :to => 'finder#alphabetized', :as => 'alphabetized'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :province, :inverse_of => :customers, :optional => true

  validates_presence_of :full_name, :image
  validates_uniqueness_of :full_name
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :customers, :inverse_of => :customer
  validates_presence_of :name
  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]
  before_action :load_provinces, :only => [:edit, :new, :update, :destroy, :create]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:full_name, :phone_number, :email_address, :image, :notes, :province_id)
  end

  def load_provinces
    @provinces = Province.order(:name)
  end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  layout 'finder_layout'

  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(:full_name)
  end

  def missing_email
    @customers = Customer.where(:email_address => [nil, ''])
  end
end

app/controllers/provinces_controller.rb
class ProvincesController < ApplicationController
  before_action :set_province, only: [:show, :edit, :update, :destroy]

  # GET /provinces
  # GET /provinces.json
  def index
    @provinces = Province.all
  end

  # GET /provinces/1
  # GET /provinces/1.json
  def show
  end

  # GET /provinces/new
  def new
    @province = Province.new
  end

  # GET /provinces/1/edit
  def edit
  end

  # POST /provinces
  # POST /provinces.json
  def create
    @province = Province.new(province_params)

    respond_to do |format|
      if @province.save
        format.html { redirect_to @province, notice: 'Province was successfully created.' }
        format.json { render :show, status: :created, location: @province }
      else
        format.html { render :new }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /provinces/1
  # PATCH/PUT /provinces/1.json
  def update
    respond_to do |format|
      if @province.update(province_params)
        format.html { redirect_to @province, notice: 'Province was successfully updated.' }
        format.json { render :show, status: :ok, location: @province }
      else
        format.html { render :edit }
        format.json { render json: @province.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /provinces/1
  # DELETE /provinces/1.json
  def destroy
    @province.destroy
    respond_to do |format|
      format.html { redirect_to provinces_url, notice: 'Province was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_province
      @province = Province.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def province_params
      params.require(:province).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/views/customers/_customer.html.haml
.customer-col-md-4
  .col-md-12.customer-container
    %p
      .pull-right
        = link_to 'edit', edit_customer_path(customer), :class => 'basic_link'
        = link_to 'x', customer_path(customer), :method => :delete, :data => { :confirm => 'Are you sure you want to delete this record?' }, :class => 'basic_link'
    %h2.customer-header-margin= customer.full_name
    = image_tag "#{customer.image}", :size => '90x120', :class => 'customer-element-margin'
    %p
      %strong Province:
      = customer.province.nil? ? 'None' : customer.province.name
    - unless customer.phone_number.blank?
      %p
        %strong Phone:
        = customer.phone_number
    - unless customer.email_address.blank?
      %p
        %strong Email:
        = customer.email_address
    - unless customer.notes.blank?
      %p
        %strong Notes:
        = customer.notes

app/views/customers/_form.html.haml
.row-fluid
  .col-md-12
    = form_with(model: customer, local: true, :html => { :class => 'customer-form'}) do |form|
      - if customer.errors.any?
        #error_explanation
          %h2
            = pluralize(customer.errors.count, "error")
            prohibited this customer from being saved:
          %ul
            - customer.errors.full_messages.each do |message|
              %li= message
      .form-group
        = form.label :full_name
        = form.text_field :full_name, id: :customer_full_name, :class => 'form-control'
      .form-group
        = form.label :phone_number
        = form.text_field :phone_number, id: :customer_phone_number, :class => 'form-control'
      .form-group
        = form.label :email_address
        = form.text_field :email_address, id: :customer_email_address, :class => 'form-control'
      .form-group
        = form.label :image
        = form.text_field :image, id: :customer_image, :class => 'form-control'
      .form-group
        = form.label :province_id
        = form.collection_select :province_id, @provinces, :id, :name, :prompt => true, :class => 'form-control'
      .form-group
        = form.label :notes
        = form.text_area :notes, id: :customer_notes, :class => 'form-control'
      .form-group
        = form.submit :class => 'btn btn-primary'
        - unless customer.new_record?
          = link_to 'Show', customer, :class => 'btn btn-default'
        = link_to 'Back', customers_path, :class => 'btn btn-default'

app/views/customers/edit.html.haml
%h1 Editing Customer
= render 'form', customer: @customer

app/views/customers/index.html.haml
%p#notice= notice
%h1
  Customers
  = link_to 'View Finder', finder_path, :class => 'basic_link'
= link_to new_customer_path, :class => 'btn btn-success btn-large pull-right' do
  %i.fa.fa-plus
  New Customer
%table.table.table-striped
  %thead
    %tr
      %th Full name
      %th Phone number
      %th Email address
      %th Image
      %th Province
      %th Notes
      %th.text-center{:width => '4%'}
  %tbody
    - @customers.each do |customer|
      %tr
        %td= customer.full_name
        %td= customer.phone_number
        %td= customer.email_address
        %td= customer.image
        %td= customer.province.nil? ? 'None' : customer.province.name
        %td= customer.notes
        %td
          .dropdown

            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              %i.fa.fa-cog

            %ul.dropdown-menu.pull-right{:role => "menu"}

              %li
                = link_to customer, :class => 'dropdown-item' do
                  %i.fa.fa-book
                  Show

              %li
                = link_to edit_customer_path(customer), :class => 'dropdown-item' do
                  %i.fa.fa-pencil-square-o
                  Edit

              %li
                = link_to customer, :class => 'dropdown-item', :method => :delete, :data => {confirm: 'Are you sure you wish to delete this customer?'} do
                  %i.fa.fa-trash
                  Delete

app/views/customers/new.html.haml
%h1 New Customer
= render 'form', customer: @customer

app/views/customers/show.html.haml
%p#notice= notice
%p
  %strong Full name:
  = @customer.full_name
%p
  %strong Phone number:
  = @customer.phone_number
%p
  %strong Email addess:
  = @customer.email_address
%p
  %strong Image:
  = @customer.image
%p
  %strong Province:
  = @customer.province.nil? ? 'None' : @customer.province.name
%p
  %strong Notes:
  = @customer.notes
= link_to 'Edit', edit_customer_path(@customer), :class => 'btn btn-primary'
= link_to 'Back', customers_path, :class => 'btn btn-default'

app/views/finder/_finder_links.html.haml
%p
  = link_to 'New Customer', new_customer_path, :class => 'basic_link'
  - unless params[:action] == 'missing_email'
    = ' - '
    = link_to 'Missing Emails', missing_emails_path, :class => 'basic_link'
  - unless params[:action] == 'alphabetized'
    = ' - '
    = link_to 'Alphabetized', alphabetized_path, :class => 'basic_link'
  - unless params[:action] == 'index'
    = ' - '
    = link_to 'All Customers', finder_path, :class => 'basic_link'

app/views/finder/_found_customers.html.haml
- @customers.each_slice(3) do |three_customers|
  .row
    - three_customers.each do |customer|
      .col-md-4
        = render :partial => 'customers/customer.html.haml', :object => customer, :as => :customer

app/views/finder/alphabetized.html.haml
%h1 Customers In Alphabetic Order
= render :partial => 'finder/finder_links'
= render :partial => 'finder/found_customers'

app/views/finder/index.html.haml
%h1 All Customers
= render :partial => 'finder/finder_links'
= render :partial => 'finder/found_customers'

app/views/finder/missing_email.html.haml
%h1 Customers Missing Emails
= render :partial => 'finder/finder_links'
= render :partial => 'finder/found_customers'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SvroomenCrm
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = yield

app/views/layouts/finder_layout.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SvroomenCrm
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .finder-layout-container
      = yield

app/views/provinces/_form.html.erb
<%= form_with(model: province, local: true) do |form| %>
  <% if province.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(province.errors.count, "error") %> prohibited this province from being saved:</h2>

      <ul>
      <% province.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :province_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/provinces/edit.html.erb
<h1>Editing Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Show', @province %> |
<%= link_to 'Back', provinces_path %>

app/views/provinces/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Provinces</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @provinces.each do |province| %>
      <tr>
        <td><%= province.name %></td>
        <td><%= link_to 'Show', province %></td>
        <td><%= link_to 'Edit', edit_province_path(province) %></td>
        <td><%= link_to 'Destroy', province, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Province', new_province_path %>

app/views/provinces/new.html.erb
<h1>New Province</h1>

<%= render 'form', province: @province %>

<%= link_to 'Back', provinces_path %>

app/views/provinces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @province.name %>
</p>

<%= link_to 'Edit', edit_province_path(@province) %> |
<%= link_to 'Back', provinces_path %>